<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseStackappCategoryAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stackapp_category_affiliate');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('affiliate_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('StackappCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('StackappAffiliate', array(
             'local' => 'affiliate_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}