<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackappCategory extends BaseStackappCategory
{
	public function getActiveJobs($max = 10)
	{
	  $q = Doctrine_Query::create()
	    ->from('StackappJob j')
	    ->where('j.category_id = ?', $this->getId())
	    ->limit($max);
	 
	  return Doctrine::getTable('StackappJob')->getActiveJobs($q);
	}

	public function countActiveJobs()
	{
	  $q = Doctrine_Query::create()
	    ->from('StackappJob j')
	    ->where('j.category_id = ?', $this->getId());
	 
	  return Doctrine::getTable('StackappJob')->countActiveJobs($q);
	}
}