<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackappCategoryTable extends Doctrine_Table
{
	public function getWithJobs()
  	{
    	$q = $this->createQuery('c')
      		->leftJoin('c.StackappJobs j')
      		->where('j.expires_at > ?', date('Y-m-d H:i:s', time()));
 
    	return $q->execute();
  	}
}