<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StackappCategory extends BaseStackappCategory
{
	public function getActiveJobs($max = 10)
	{
	  $q = $this->getActiveJobsQuery()
	    ->limit($max);
	 
	  return $q->execute();
	}
	 
	public function countActiveJobs()
	{
	  return $this->getActiveJobsQuery()->count();
	}

	public function getActiveJobsQuery()
	{
	  $q = Doctrine_Query::create()
	    ->from('StackappJob j')
	    ->where('j.category_id = ?', $this->getId());
	 
	  return Doctrine::getTable('StackappJob')->addActiveJobsQuery($q);
	}
}