<?php
// auto-generated by sfRoutingConfigHandler
// date: 2013/07/21 20:07:20
return array(
'stackapp_affiliate_update' => new sfDoctrineRouteCollection(array (
  'model' => 'StackappAffiliate',
  'module' => 'update',
  'prefix_path' => 'update',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'stackapp_affiliate_update',
  'requirements' => 
  array (
  ),
)),
'stackapp_category_category' => new sfDoctrineRouteCollection(array (
  'model' => 'StackappCategory',
  'module' => 'category',
  'prefix_path' => 'category',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'stackapp_category_category',
  'requirements' => 
  array (
  ),
)),
'stackapp_job_job' => new sfDoctrineRouteCollection(array (
  'model' => 'StackappJob',
  'module' => 'job',
  'prefix_path' => 'job',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'stackapp_job_job',
  'requirements' => 
  array (
  ),
)),
'homepage' => new sfRoute('/', array (
  'module' => 'job',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
