<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/21 20:07:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=stackappv4',
  'username' => 'root',
  'password' => '407',
  'classname' => 'DebugPDO',
  'name' => 'doctrine',
)),);
