dev:
  doctrine:
    param:
      classname: DebugPDO
test:
  doctrine:
    param:
      classname: DebugPDO
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=stackappv4'
      username: root
      password: '407'
