<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/07/21 20:08:48
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 2,
  'app_max_jobs_on_category' => 10,
));
