<?php
// auto-generated by sfRoutingConfigHandler
// date: 2013/07/21 20:08:50
return array(
'category' => new sfDoctrineRoute('/category/:slug', array (
  'module' => 'category',
  'action' => 'show',
), array (
), array (
  'model' => 'StackappCategory',
  'type' => 'object',
)),
'job_show_user' => new sfDoctrineRoute('/job/:company_slug/:location_slug/:id/:position_slug', array (
  'module' => 'job',
  'action' => 'show',
), array (
  'id' => '\\d+',
  'sf_method' => 
  array (
    0 => 'GET',
  ),
), array (
  'model' => 'StackappJob',
  'type' => 'object',
  'method_for_query' => 'retrieveActiveJob',
)),
'job' => new sfDoctrineRouteCollection(array (
  'model' => 'StackappJob',
  'column' => 'token',
  'object_actions' => 
  array (
    'publish' => 'put',
  ),
  'name' => 'job',
  'requirements' => 
  array (
    'token' => '\\w+',
  ),
)),
'job_search' => new sfRoute('/search', array (
  'module' => 'job',
  'action' => 'search',
), array (
), array (
)),
'update' => new sfDoctrineRouteCollection(array (
  'model' => 'StackappAffiliate',
  'actions' => 
  array (
    0 => 'new',
    1 => 'create',
  ),
  'object_actions' => 
  array (
    'wait' => 'get',
  ),
  'name' => 'update',
  'requirements' => 
  array (
  ),
)),
'homepage' => new sfRoute('/', array (
  'module' => 'job',
  'action' => 'index',
), array (
), array (
)),
);
